
name: daku
description: A tinder for Products

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_plyr_iframe: ^2.0.0
  graphql_flutter:
  rive: ^0.6.8
  url_strategy: ^0.2.0
  google_fonts:
  url_launcher:
  swipable_stack: 0.3.0
  hive:
  provider:
  cached_network_image:
  rive_splash_screen: ^0.0.1
  flutter_icons: ^1.1.0
  sqflite: ^2.0.0+3
  get: ^4.1.2
  get_storage: ^2.0.2
  fluttertoast: ^8.0.6
  webview_flutter: ^2.0.4
  device_preview: ^0.7.1
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.2
  percent_indicator: ^3.0.1
  sign_button: ^2.0.0


  app_links: ^2.0.0
  shared_preferences: ^2.0.0
  nhost_flutter_auth: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  rename:
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/riv/
